/* Generated by tools/xxx.py */

#ifndef PYTHON_DYNLOAD_NPVAR_H
#define PYTHON_DYNLOAD_NPVAR_H

/* Define non-pointer variables via macros */
#define Py_OptimizeFlag (*Py_OptimizeFlag_Ptr)

#endif  // PYTHON_DYNLOAD_NPVAR_H

/* Define non-pointer variables' help variables via macros */
#ifdef  DATA_PTR
DATA_PTR(int, Py_OptimizeFlag);
#endif
